"""Topic bank for Spanish conversation practice — 50 topics per CEFR level group."""

TOPICS_BY_CEFR: dict[str, list[str]] = {
    "A0": [
        "First Meeting",
        "My Name",
        "Saying Goodbye",
        "Your Favorite Color",
        "My Family",
        "My Pet",
        "A Big Smile",
        "Hello and Goodbye",
        "I Am Happy",
        "My Sister and Brother",
        "Red, Blue, or Green?",
        "Mom and Dad",
        "My Dog",
        "Is It Big or Small?",
        "Good Morning",
        "My Grandmother",
        "Yes or No",
        "Two Friends Meet",
        "My Cat",
        "The Yellow Sun",
        "I Have a Friend",
        "A Short Introduction",
        "My Baby Brother",
        "Old or New?",
        "Short and Tall",
        "My Uncle and Aunt",
        "Morning Greeting",
        "My Favorite Animal",
        "Nice to Meet You",
        "At Home",
        "A New Classmate",
        "Goodbye, See You",
        "Colors in the Room",
        "My Parents",
        "I Like Dogs",
        "Is She Happy?",
        "My New Friend",
        "The Green Tree",
        "My Little Sister",
        "A Friendly Wave",
        "My Name Is...",
        "How Are You?",
        "My Favorite Color Is Blue",
        "Meet My Family",
        "I Am Fine, Thanks",
        "Good Afternoon",
        "My Brother's Name",
        "I See a Cat",
        "Hello, I Am...",
        "This Is My Friend",
    ],
    "A1": [
        "My Morning Routine",
        "What Do You Like to Eat?",
        "At the Market",
        "My Favorite Sport",
        "After School Activities",
        "Weekend Plans",
        "The Weather Today",
        "My Best Friend",
        "A Trip to the Zoo",
        "My Bedroom",
        "Learning Something New",
        "Going to School",
        "I Love Reading",
        "Cooking at Home",
        "Playing Games",
        "A Walk in the Park",
        "Swimming Lessons",
        "My Favorite Food",
        "Watching a TV Show",
        "My Hobby",
        "A Rainy Day",
        "Sunday Afternoon",
        "Making Lunch",
        "My School Subjects",
        "A Sunny Day",
        "Drawing and Painting",
        "Riding a Bike",
        "My Favorite Season",
        "Evening at Home",
        "Going to the Library",
        "My Favorite Drink",
        "A Day at the Beach",
        "Playing Football",
        "Cats or Dogs?",
        "Cooking Breakfast",
        "My Classroom",
        "Listening to Music",
        "Shopping for Clothes",
        "A Picnic in the Park",
        "My Best Day",
        "Saturday Morning",
        "My Favorite Movie",
        "Visiting the Doctor",
        "Learning to Cook Paella",
        "At the Playground",
        "What Do You Do After School?",
        "Reading Before Bed",
        "Helping at Home",
        "My Favorite Holiday",
        "A Fun Weekend",
    ],
    "A2": [
        "My Last Vacation",
        "A Special Birthday Party",
        "What I Did Last Weekend",
        "My Daily Routine",
        "Shopping in the City",
        "A Restaurant Visit",
        "Getting to School",
        "A Holiday Abroad",
        "My Childhood Home",
        "Giving Directions",
        "Planning a Weekend Trip",
        "Last Summer Holiday",
        "A Memorable Meal",
        "A Day Off Work",
        "Travel by Train",
        "Going to the Cinema",
        "Supermarket Shopping",
        "My First Day at School",
        "A Rainy Holiday",
        "A Family Gathering",
        "My Favorite Childhood Memory",
        "Learning to Drive",
        "Moving to a New Place",
        "A Visit to the Museum",
        "A Bus Journey",
        "A Birthday Celebration",
        "Cooking a Special Meal",
        "A Day at the Farm",
        "Camping Last Summer",
        "A Sports Event",
        "Shopping for a Gift",
        "A Road Trip",
        "My Work Day",
        "Finding a Good Restaurant",
        "The Best Holiday I Remember",
        "When I Was a Child",
        "A Surprise Party",
        "Learning Something Difficult",
        "Missing the Bus",
        "A Night Out",
        "Visiting a New City",
        "Booking a Hotel Room",
        "A Bad Weather Day",
        "Packing for a Trip",
        "An Outdoor Adventure",
        "My Favorite Childhood Game",
        "Starting a New Hobby",
        "A Trip to the Market",
        "My Weekend Routine",
        "A Memory from School",
    ],
    "B1": [
        "My Dream Job",
        "A Life-Changing Experience",
        "Planning for the Future",
        "If I Could Travel Anywhere",
        "Comparing Cities",
        "Health and Fitness Goals",
        "My Greatest Achievement",
        "A Difficult Decision",
        "Learning a New Language",
        "Working from Home",
        "Starting a Business",
        "Advice from a Friend",
        "Balancing Work and Life",
        "Moving Abroad",
        "My Career Path",
        "Things I Have Always Wanted to Do",
        "Overcoming a Challenge",
        "Volunteering Experience",
        "An Unforgettable Trip",
        "Job Interview Preparation",
        "Long-Distance Friendship",
        "Learning from Mistakes",
        "City Life vs. Country Life",
        "Changing a Bad Habit",
        "A New Hobby I Discovered",
        "Social Media: Good or Bad?",
        "Books vs. Movies",
        "My Environmental Habits",
        "An Event That Changed Me",
        "Working in a Team",
        "My Goals for This Year",
        "A Disagreement with Someone",
        "Making New Friends as an Adult",
        "My Favorite Way to Relax",
        "Planning a Big Event",
        "Managing Stress",
        "A Proud Moment in My Life",
        "Childhood Dreams vs. Reality",
        "A City I Would Like to Live In",
        "My Experience with Online Learning",
        "An Unexpected Adventure",
        "Trying a New Sport",
        "A Personal Challenge I Faced",
        "Reconnecting with an Old Friend",
        "A Time I Helped Someone",
        "Living Alone for the First Time",
        "Traveling Solo vs. with Others",
        "Hispanic Culture and Traditions",
        "A Skill I Want to Learn",
        "Reflecting on Last Year",
    ],
    "B2": [
        "The Impact of Social Media on Society",
        "Climate Change: What Can We Do?",
        "Artificial Intelligence in Daily Life",
        "Remote Work: Pros and Cons",
        "Diversity and Inclusion at Work",
        "Mental Health in Modern Society",
        "The Future of Education",
        "Urban vs. Rural Living",
        "Living a Sustainable Lifestyle",
        "Technology and Privacy",
        "The Challenges of Entrepreneurship",
        "Immigration and Cultural Integration",
        "Media Bias and Fake News",
        "Work-Life Balance Today",
        "Ethical Consumption",
        "The Gig Economy",
        "Youth and Political Participation",
        "Economic Inequality in Latin America",
        "Effects of Globalization",
        "Digital Wellbeing",
        "Gender Equality in the Workplace",
        "Healthcare Systems Debate",
        "The Role of Art in Society",
        "Cybersecurity Risks",
        "Animal Rights and Ethics",
        "Space Exploration: Worth It?",
        "The Rise of Influencer Culture",
        "Education Reform Debates",
        "Freedom of Speech Online",
        "Environmental Activism",
        "The Housing Crisis",
        "Self-Driving Cars",
        "The Ethics of Genetic Engineering",
        "Corporate Social Responsibility",
        "Vaccination and Public Health",
        "The Renewable Energy Transition",
        "Cultural Appropriation",
        "The Future of Work",
        "Technology Addiction",
        "Public Transport vs. Private Cars",
        "Universal Basic Income: A Good Idea?",
        "Social Mobility in Latin America",
        "Consumerism and Its Consequences",
        "Women's Roles in Society Today",
        "Global Food Security",
        "Nuclear Energy: Safe or Not?",
        "Automation and Job Displacement",
        "The Digital Divide",
        "An Ethical Dilemma at Work",
        "Balancing Security and Privacy",
    ],
    "C1": [
        "The Paradox of Choice",
        "Cultural Identity in Latin America",
        "The Philosophy of Happiness",
        "Moral Relativism vs. Universal Ethics",
        "Latin American Literature as Social Commentary",
        "The Nature of Creativity",
        "Does Language Shape Thought?",
        "Political Satire in Hispanic Media",
        "The Ethics of Whistleblowing",
        "Artificial Intelligence and Consciousness",
        "The Concept of Time Across Cultures",
        "Capitalism vs. Socialism: Economic Systems Compared",
        "The Science of Persuasion",
        "Magic Realism in Literature",
        "Memory and Personal Identity",
        "The Psychology of Leadership",
        "Technological Determinism",
        "Civil Disobedience: Justified or Not?",
        "Tradition vs. Modernity in Hispanic Culture",
        "Theories of Justice",
        "Humor Across Spanish-Speaking Cultures",
        "How Architecture Influences Behavior",
        "Cognitive Biases in Decision-Making",
        "The Concept of Freedom in Philosophy",
        "Media Representation and Stereotypes",
        "The Ethics of Artificial Intelligence",
        "Cultural Diplomacy",
        "The Rise of Nationalism in Latin America",
        "Moral Courage",
        "Philosophy of Mind",
        "Regional Dialects and Language Variation",
        "The Politics of Language",
        "Dystopian Fiction and Modern Society",
        "The Spanish Enlightenment and Its Legacy",
        "Scientific Progress and Ethics",
        "The Psychology of Conformity",
        "Social Justice Movements in Latin America",
        "Religion in the Modern Hispanic World",
        "What Is Beauty? Aesthetics and Philosophy",
        "Globalization and Cultural Homogenization",
        "Existentialism in Daily Life",
        "Power, Corruption, and Accountability",
        "The Limits of Democracy",
        "Narrative and Personal Identity",
        "Futurism and Utopian Thinking",
        "Colonialism and Its Legacy in Latin America",
        "Nature vs. Nurture: The Ongoing Debate",
        "Eco-Philosophy and Environmental Ethics",
        "Empathy: Its Limits and Possibilities",
        "The Sociology of Fame",
    ],
    "C2": [
        "Deconstruction and Meaning in Literature",
        "The Ethics of Memory and Forgetting",
        "What Is Truth? Philosophy of Language",
        "Metacognition and Self-Awareness",
        "The Role of Myth in Contemporary Culture",
        "Aesthetics and Subjective Experience",
        "Quantum Physics and Philosophy",
        "The Rhetoric of Political Speeches",
        "Intertextuality in Latin American Literature",
        "The Phenomenology of Perception",
        "Utopias and Their Inevitable Failures",
        "Moral Obligations to Future Generations",
        "Psycholinguistics and Language Acquisition",
        "The Concept of the Self Across Cultures",
        "Epistemology: What Can We Really Know?",
        "Dark Humor as Social Commentary",
        "The Philosophy of Time",
        "Dialectical Thinking in History",
        "The Paradox of Tolerance",
        "Latin American Literary Modernism and Its Critics",
        "Consciousness, Determinism, and Free Will",
        "The Ethics of Genetic Enhancement",
        "Social Contract Theory",
        "Language Death and Revitalization in Indigenous Languages",
        "The Anthropology of Art",
        "Metaphysics and the Nature of Reality",
        "Satire in 21st Century Hispanic Media",
        "Philosophy of Science: What Is a Theory?",
        "The Post-Truth Society",
        "Chaos Theory and Determinism",
        "The Semiotics of Visual Culture",
        "Tragedy and Catharsis in Literature",
        "The Sociology of Knowledge",
        "Nihilism, Absurdism, and Meaning",
        "Dialectical Materialism",
        "The Hermeneutic Circle",
        "The Politics of Nostalgia",
        "Narrative Ethics in Fiction",
        "Bioethics in the 21st Century",
        "Interdisciplinary Thinking and Innovation",
        "Language, Power, and Social Identity",
        "The Philosophy of Love",
        "Solipsism and the Problem of Other Minds",
        "The Aesthetics of Music",
        "Transcendentalism: Nature and the Self",
        "Anarchism in Latin American Political Thought",
        "The Idea of Progress in Western Thought",
        "Comparative Mythology",
        "The Limits of Human Perception",
        "Philosophy of Economics and Value",
    ],
}
